### ISSUE TITLE
Naming conflict for SecurityMarksName

### ISSUE THREAD

**Issue by kolea2** [googleapis/java-securitycenter#207]
Capitalization of the class is different in v1beta1 and v1 which is causing conflicts:

https://github.com/googleapis/java-securitycenter/blob/master/proto-google-cloud-securitycenter-v1beta1/src/main/java/com/google/cloud/securitycenter/v1beta1/SecuritymarksName.java
https://github.com/googleapis/java-securitycenter/blob/master/proto-google-cloud-securitycenter-v1/src/main/java/com/google/cloud/securitycenter/v1/SecurityMarksName.java

**Comment by Neenu1995** [comment]
This is scheduled to be fixed during next major release to avoid breaking changes.
